#plumber: "https://www.indeed.com/jobs?q=plumber&explvl=mid_level"
#computer-engineer: "https://www.indeed.com/jobs?q=computer%20scientist&explvl=mid_level"
nurse: "https://www.indeed.com/jobs?q=nurse&explvl=mid_level"
#oil-field-engineer: "https://www.indeed.com/jobs?q=oil%20field%20engineer&explvl=mid_level"
#clerk: "https://www.indeed.com/jobs?q=clerk&explvl=mid_level"
#graphic-designer: "https://www.indeed.com/jobs?q=graphic%20designer&explvl=mid_level"
#doctor: "https://www.indeed.com/jobs?q=doctor&explvl=mid_level"
#bartender: "https://www.indeed.com/jobs?q=bartender&explvl=mid_level"
#Customer-Service-Representative: "https://www.indeed.com/jobs?q=customer%20service%20representative&explvl=mid_level"
#house-cleaner: "https://www.indeed.com/jobs?q=house%20cleaner&explvl=mid_level"