plumber: "https://www.indeed.com/jobs?q=plumber"
computer-engineer: "https://www.indeed.com/jobs?q=computer%20scientist"
nurse: "https://www.indeed.com/jobs?q=nurse"
oil-field-engineer: "https://www.indeed.com/jobs?q=oil%20field%20engineer"
clerk: "https://www.indeed.com/jobs?q=clerk"
graphic-designer: "https://www.indeed.com/jobs?q=graphic%20designer"
doctor: "https://www.indeed.com/jobs?q=doctor"
bartender: "https://www.indeed.com/jobs?q=bartender"
Customer-Service-Representative: "https://www.indeed.com/jobs?q=customer%20service%20representative"
house-cleaner: "https://www.indeed.com/jobs?q=house%20cleaner"